### ISSUE TITLE
Unexpected OAuth service evernote

### ISSUE THREAD

**Issue by anthon** [priezz/meteor-accounts-evernote#1]
Running Meteor 1.2.0.2, and keep getting

```
W20151022-09:56:16.741(2) (oauth_server.js:398) Error in OAuth Server:
Unexpected OAuth service evernote
```

Other accounts-\* work fine, and env is set to development. Any ideas?

**Comment by anthon** [comment]
Ok, seems like some internal load order cache issue; adding `evernote` separately solved the issue.

**Comment by kylehayes** [comment]
@anthon, I'm having this same problem, what do you mean by adding `evernote` separately solved the problem?

**Comment by priezz** [comment]
@kylehayes, this means, you have to add both, accounts-evernote and evernote packages to your project:
`meteor add evernote accounts-evernote`

P.S. I have to mention this in README...

**Comment by kylehayes** [comment]
Hmm, I don't think it worked for me. I'll try it again just to be sure.

**Comment by anthon** [comment]
Sorry for the delay – yes, I guess that's what I meant; explicitly adding both the `evernote` and `accounts-evernote` packages solved it for me. Unfortunately I don't have the code to confirm it right now. Lost everything in a silly manoeuvre when switching backup system...
