### ISSUE TITLE
Exception while invoking 'login'

### ISSUE THREAD

**Issue by kylehayes** [priezz/meteor-accounts-evernote#2]
I'm brand new to Meteor so not sure if I'm even booting this properly. I created a fresh project, change to the project directory and executed:
`meteor add accounts-base accounts-oauth priezz:evernote priezz:accounts-evernote accounts-ui`

Then in the project's HTML file, I added `{{> loginButtons}}`. When I started the server, I clicked the login with Evernote and configured the credentials. When I returned to the page to attempt to login, a window pops up and suddenly closes leaving the following error in the terminal:

```
W20160111-16:00:08.804(-8) (oauth_server.js:398) Error in OAuth Server: Failed to send OAuth1 request to https://www.evernote.com/oauth. failed [401] <html> <head> <meta charset="utf-8" /> <meta http-equiv="X-UA-Compatible" content="IE=9,chrome=1" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" /> <link rel="stylesheet" href="/redesign/global/css/reset.css" />  <link rel="stylesheet" href="/redesign/global/css/fonts.css" media="all" />  <link rel="stylesheet" href="/redesign/global/css/header.css" /> <link rel="stylesheet" href="/redesign/global/css/lay...
I20160111-16:00:09.104(-8)? Exception while invoking method 'login' Error: Failed to send OAuth1 request to https://www.evernote.com/oauth. failed [401] <html> <head> <meta charset="utf-8" /> <meta http-equiv="X-UA-Compatible" content="IE=9,chrome=1" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" /> <link rel="stylesheet" href="/redesign/global/css/reset.css" />  <link rel="stylesheet" href="/redesign/global/css/fonts.css" media="all" />  <link rel="stylesheet" href="/redesign/global/css/header.css" /> <link rel="stylesheet" href="/redesign/global/css/lay...
I20160111-16:00:09.105(-8)?     at [object Object].OAuth1Binding._call (packages/oauth1/oauth1_binding.js:175:1)
I20160111-16:00:09.105(-8)?     at [object Object].OAuth1Binding.prepareRequestToken (packages/oauth1/oauth1_binding.js:28:1)
I20160111-16:00:09.105(-8)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth1/oauth1_server.js:24:1)
I20160111-16:00:09.105(-8)?     at middleware (packages/oauth/oauth_server.js:173:1)
I20160111-16:00:09.105(-8)?     at packages/oauth/oauth_server.js:146:1
```

**Comment by priezz** [comment]
Usually this means, that you have no sufficient rights for Evernote API. If you are using Evernote sandbox service, do not forget to set "sandbox: true" in 'evernote' service configuration (Mongo/meteor_accounts_loginServiceConfiguration).

**Comment by kylehayes** [comment]
I wasn't quite sure what you meant by `Mongo/meteor_accounts_loginServiceConfiguration` but after some digging I learned this configuration is stored in mongo so I set the value manually. Were you referring to another method to set it?

Once I did set sandbox to true and restarted the server, the popup showed properly with Evernote's login page. Thank you!

**Comment by priezz** [comment]
That is exactly what I wrote :) You Mongo db, meteor_accounts_loginServiceConfiguration collection, evernote service record.

Welcome! But I still have to update the README for better process explanation...

**Comment by kylehayes** [comment]
Great—I appreciate your patience. Thanks for the help—I was successfully able to login to the sandbox environment.
